server:
  port: 8080
  context-path: /spring-web-security
com:
  jin:
    siteminder:
      restClient:
        protocol: https
        host: sso.staples.com
        port: 443
        appRoot: /ssorest/service/sso
        requireAuth : false
    web:
      session:
        maxInactiveInterval: 1500
      security:
        url:
          loginUrl: /login
          noAuthWebUrlsPattern: /, /home
          apiUrlPrefix: /api
spring:
  application:
    name: spring-web-security
  redis:
    host: localhost
    port: 6379
management:
  security:
    enabled: false
logging:
  file: ./target/spring-web-security.log